### ISSUE TITLE
Clean up code base

### ISSUE THREAD

**Issue by letientai299** [biryu2205/training#3]
I understand that you have picked a wrong artifact when generate maven project. But we can clean it up.

- Remove folder that you don't use.
- Check the `pom.xml` file, remove any dependencies that you don't use. (Hint: you only need junit).

**Comment by biryu2205** [comment]
Can you teach me how to create a maven project correctly again?.I have some problems with my project.Thank you

**Comment by letientai299** [comment]
After you finish those tasks and if we have time.

**Comment by letientai299** [comment]
After you finish those tasks and if we have time.
