### ISSUE TITLE
Help in write Test Junit 

### ISSUE THREAD

**Issue by biryu2205** [biryu2205/training#4]
![image](https://user-images.githubusercontent.com/21965505/32537132-ff81e962-c493-11e7-95b1-5bd1bf33cb76.png)
I have a problem when i try to write test like this. Can you help me please?
thank you.

**Comment by letientai299** [comment]
Check your syntax. Is that a "method"?

**Comment by biryu2205** [comment]
I already resolve that problem,but look like i have a problem in write a test for String Result,i mean compare string in Test

**Comment by letientai299** [comment]
Code? For whatever question, think about if I have enough information to help you, so that we don't waste time on those reminder like this.

**Comment by biryu2205** [comment]
![image](https://user-images.githubusercontent.com/21965505/32537757-5172c320-c496-11e7-9d5f-8bb26332a7f5.png)
![image](https://user-images.githubusercontent.com/21965505/32537808-772fabe6-c496-11e7-9fe6-d71c02af91cd.png)

**Comment by letientai299** [comment]
Only code, with markdown fence. Save bandwidth.

**Comment by biryu2205** [comment]
WelcomeToJava
```java
public class WelcomeToJava {
  public static String printHello1() {
    String str1;
    str1 = "Hello, World.";
    return str1;
  }

  public static String printHello2() {
    String str2;
    str2 = "Hello, Java.";
    return str2;
  }

  public static void main(String[] args) {
    System.out.println(printHello1());
    System.out.println(printHello2());
  }
}
```
WelcomeToJavaTest
```java
import org.junit.Test;

import static org.junit.Assert.*;

public class WelcomeToJavaTest {
  @Test
  public void printHello1()  {
    assertEquals("Hello, World.",printHello1());
  }

  private void assertEquals(String s, void aVoid) {
  }

  @Test
  public void printHello2()  {
  }
}
```

**Comment by letientai299** [comment]
What is the IDE tell you about the error?

Note: See, I still don't have enough info, and have to ask you again.

**Comment by biryu2205** [comment]
At 
```java 
assertEquals("Hello, World.",printHello1());
```

It's say cannot resolve method ' assertEquals(java.lang.String,void)'
But the printHello1 return str1, I dont know why.

**Comment by letientai299** [comment]
Format. And don't use abbreviation. Full text, with capitalized first letter per sentence and dot at the end.

**Comment by letientai299** [comment]
If you need help, you should do your best to save effort for the people who want to help you. Don't be careless.

**Comment by letientai299** [comment]
Still not satisfy my eyes. 
>  But the printHello1 return str1, i dont know why.

- Method name and variable: `printHello1`, `str1`
- "i" in lower case?
- "dont"?

**Comment by biryu2205** [comment]
Okay,I will take care about this.

**Comment by letientai299** [comment]
Fix it now.

**Comment by letientai299** [comment]
You forget to import static method from your original class. `printHello1` is not part of your test class. And don't forget to fix all the fucking typos before closing this issue.
