### ISSUE TITLE
Remove .idea from git

### ISSUE THREAD

**Issue by letientai299** [biryu2205/training#6]
That folder stores your local IDEA config, and your workspace state, which is subjected to change very frequently, and not what we're interesting for the long term.

**Comment by biryu2205** [comment]
__Need Help!__

Can you teach me how can I create an .gitignore and work with it?
Thank you!

**Comment by letientai299** [comment]
```sh
$ # create file.
$ touch .gitignore
$ # verify that you have a .gitignore in your git project folder.
$ ls -lah 
$ # Open that file for editing
$ gedit .gitignore
$ # Of course, you can just open project in the IDE and use IDE to edit the .gitignore file.
````

**Comment by letientai299** [comment]
Well done.
